[tool.poetry]
name = "qbpm"
version = "1.0rc2"
description = "qutebrowser profile manager"
authors = ["Peter Rice <peter@peterrice.xyz>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/pvsr/qpm"
repository = "https://github.com/pvsr/qpm"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8"
pyxdg = "^0.27"

[tool.poetry.group.dev.dependencies]
mypy = "^0.991"
black = "^22.12.0"
pytest = "^7.2.0"
pylint = "^2.15.9"
isort = "^5.11.4"

[build-system]
requires = ["poetry-core>=1.0.0", "setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
qbpm = "qbpm.main:main"

[tool.setuptools_scm]
write_to = "qbpm/version.py"

[tool.isort]
profile = "black"
