select = ["E", "F", "W", "I", "UP", "N", "ANN", "S", "B", "A", "C4", "PT", "SIM", "ARG"]
target-version = "py39"
ignore = [
  "E501", # line too long
  "ANN101", # annotate self
  "ANN102", # annotate cls
  "ANN401", # ban Any
]

[per-file-ignores]
"tests/test_main.py" = [ "S101", "ANN201"]
"tests/test_profiles.py" = [ "S101", "ANN201"]
